// foxbridge-bootstrap.mjs — generates the Camoufox launch config the same
// way the camofox server does: calls camoufox-js' launchOptions() (the
// exact function at jo-inc/camofox-browser server.js:1057) with the
// production flags (humanize, enable_cache, headed via Xvfb).
//
// Outputs (written to /etc so the entrypoint can source them):
//   /etc/foxbridge-env     — CAMOU_CONFIG_1..N + FONTCONFIG_PATH + DISPLAY
//   /etc/foxbridge-execpath — Camoufox executable path
//   <profile>/user.js      — firefoxUserPrefs (cache prefs, webgl, ...)
//
// The CAMOU_CONFIG JSON includes the addons list (UBO path), which the
// patched Camoufox binary reads itself — that is what actually loads
// uBlock Origin (a static CAMOU_CONFIG_1 with a pinned fingerprint does
// NOT register the addon; launchOptions() regenerates seeds and addons).
import { writeFileSync, mkdirSync } from "node:fs";
import { launchOptions } from "/app/node_modules/camoufox-js/dist/utils.js";

const profile = process.env.FOXBRIDGE_PROFILE || "/profile";
const outdir = process.env.FOXBRIDGE_OUTDIR || "/etc";

const opts = await launchOptions({
  executable_path: process.env.FOXBRIDGE_EXECUTABLE || "/root/.cache/camoufox/camoufox-bin",
  os: "linux",
  headless: false,
  humanize: true,
  enable_cache: true,
  virtual_display: process.env.DISPLAY || ":0",
});

// 1) firefoxUserPrefs -> user.js in the profile (Foxbridge passes
//    --profile to Camoufox; user.js is read at profile init)
mkdirSync(profile, { recursive: true });
const prefs = Object.entries(opts.firefoxUserPrefs || {})
  .map(([k, v]) => `user_pref("${k}", ${JSON.stringify(v)});`)
  .join("\n");
writeFileSync(`${profile}/user.js`, `// generated by foxbridge-bootstrap ${new Date().toISOString()}\n${prefs}\n`);

// 2) env -> sourced by the entrypoint (only what Camoufox needs)
const keep = (k) => k.startsWith("CAMOU_CONFIG") || k === "FONTCONFIG_PATH" || k === "DISPLAY";
const envLines = Object.entries(opts.env).filter(([k]) => keep(k))
  .map(([k, v]) => `${k}=${JSON.stringify(v)}`);
writeFileSync(`${outdir}/foxbridge-env`, envLines.join("\n") + "\n");

// 3) executable path
writeFileSync(`${outdir}/foxbridge-execpath`, opts.executablePath);

// summary for the container log
const chunks = Object.keys(opts.env).filter((k) => k.startsWith("CAMOU_CONFIG"));
console.log(`[bootstrap] exec=${opts.executablePath}`);
console.log(`[bootstrap] CAMOU_CONFIG chunks=${chunks.length} (${chunks.join(",")})`);
console.log(`[bootstrap] FONTCONFIG_PATH=${opts.env.FONTCONFIG_PATH}`);
console.log(`[bootstrap] prefs=${Object.keys(opts.firefoxUserPrefs || {}).length} keys -> ${profile}/user.js`);
